Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: obar-demo-bucket

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0146fc9ad419e2cfd
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-00e0dccbb362e8531
          GroupSet:
            - sg-08021b8c54cfaf441